#!/usr/bin/env bash
# create loop with while
i=0
while [ $i -le 10 ]
do
	if [ $i == 3 ]
	then
		echo bad luck
	elif [ $i == 8 ] 
	then
		echo good luck
	else
		echo Best School
	fi
	i=$(( i + 1 ))
done
