#!/usr/bin/env bash
# create loop with while and case
COUNTRY=1
while [ $COUNTRY -le 20 ]
do
	echo $COUNTRY
	case $COUNTRY in
		 4)
			 echo bad luck from China 
		;;

		9)
			echo bad luck from Japan
		;;
		17)
			echo bad luck from Italy
		;;
		
	esac
		COUNTRY=$(( COUNTRY + 1 ))
done

