#!/usr/bin/env bash
#create file and after kill this file 
file="/var/run/mysript.pid"
touch $file > "$BASHPID"
while true
do
    echo "To  and beyond"
    sleep 2
    trap 'echo "I hate the kill command"; rm $file ; exit' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
done
