#!/usr/bin/env bash
#create file and after kill this file 
file="/var/run/myscript.pid"
touch $file > "$BASHPID"
while true
do
	echo 'To infinity and beyond'
	trap 'echo I hate the kill command ; rm $file ; exit ' SIGTERM
	trap 'echo Y U no love me?! ; rm $file ; exit ' SIGINT
done
